### ISSUE TITLE
exception while copying value

### ISSUE THREAD

**Issue by wajahatch888** [binxio/aws-ssm-copy#2]
I have installed the utility from pip. While performing --dry-run it is showing correct values but executing the command without --dry-run it is throwing an exception.

**Command with a dry run and it's result**
Command: aws-ssm-copy --source-profile test1 --recursive --overwrite /test/ --source-region us-west-2 --region us-west-2 --profile test1 --target-path /test-v2/ --dry-run

Result: INFO: copying /test/first to /test-v2/first

**Command without dry run** 
Command: aws-ssm-copy --source-profile test1 --recursive --overwrite /test/ --source-region us-west-2 --region us-west-2 --profile test1 --target-path /test-v2/ 

**Exception:**
aws-ssm-copy` --source-profile test1 --recursive --overwrite /test/ --source-region us-west-2 --region us-west-2 --profile test1 --target-path /test-v2/
INFO: copying /test/second to /test-v2/second
Traceback (most recent call last):
  File "/usr/local/bin/aws-ssm-copy", line 11, in <module>
    load_entry_point('aws-ssm-copy==0.2.2', 'console_scripts', 'aws-ssm-copy')()
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 182, in main
    cp.main()
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 173, in main
    options.overwrite,
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 97, in copy
    self.target_ssm.put_parameter(**parameter)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Policies, value: [{u'PolicyStatus': u'Pending', u'PolicyText': u'{"Type":"NoChangeNotification","Version":"1.0","Attributes":{"After":"5","Unit":"Days"}}', u'PolicyType': u'NoChangeNotification'}, {u'PolicyStatus': u'Pending', u'PolicyText': u'{"Type":"Expiration","Version":"1.0","Attributes":{"Timestamp":"2019-06-01T12:00:00Z"}}', u'PolicyType': u'Expiration'}], type: <type 'list'>, valid types: <type 'basestring'>
[ec2-user@ip-172-31-27-112 .aws]$ clear

[ec2-user@ip-172-31-27-112 .aws]$ aws-ssm-copy --source-profile test1 --recursive --overwrite /test/ --source-region us-west-2 --region us-west-2 --profile test1 --target-path /test-v2/ --dry-run
INFO: copying /test/first to /test-v2/first
[ec2-user@ip-172-31-27-112 .aws]$ aws-ssm-copy --source-profile test1 --recursive --overwrite /test/ --source-region us-west-2 --region us-west-2 --profile test1 --target-path /test-v2/
INFO: copying /test/first to /test-v2/first
Traceback (most recent call last):
  File "/usr/local/bin/aws-ssm-copy", line 11, in <module>
    load_entry_point('aws-ssm-copy==0.2.2', 'console_scripts', 'aws-ssm-copy')()
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 182, in main
    cp.main()
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 173, in main
    options.overwrite,
  File "/usr/local/lib/python2.7/site-packages/aws_ssm_copy/copy.py", line 97, in copy
    self.target_ssm.put_parameter(**parameter)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Policies, value: [], type: <type 'list'>, valid types: <type 'basestring'>

**Comment by khalithsuth** [comment]
Guys any update on the above issue as even am also facing the same issue. Please help...

**Comment by mvanholsteijn** [comment]
Hi please try to install the utility in a Python 3.7 environment.

**Comment by captain-sysadmin** [comment]
Hi @mvanholsteijn I don't think its a python3.7 issue, it appears to be how boto3 deals with policies. The attached PR _should_ fix it. (well it does for me, we don't have many policies, so I'm not sure how it handles all cases.)
