### ISSUE TITLE
How to install this tool on macos?

### ISSUE THREAD

**Issue by igal1c0de4n** [binxio/aws-ssm-copy#31]
Some google searches indicated installing via:
```
pip install aws-ssm-copy
```
However when I try to run it:
```
$ aws-ssm-copy -h
Traceback (most recent call last):
  File "/Users/igal/.pyenv/versions/2.7.18/bin/aws-ssm-copy", line 11, in <module>
    load_entry_point('aws-ssm-copy==0.5.2', 'console_scripts', 'aws-ssm-copy')()
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/aws_ssm_copy/__init__.py", line 1, in <module>
    from aws_ssm_copy.ssm_copy import main
  File "/Users/igal/.pyenv/versions/2.7.18/lib/python2.7/site-packages/aws_ssm_copy/ssm_copy.py", line 53
    result["Name"] = re.sub(regex, f"/{tp}/", parameter["Name"])
                                           ^
SyntaxError: invalid syntax
```
Any tips?

**Comment by Fmacmak** [comment]
Can you try with a different version of python >v3.6? (I use python3.9)

**Comment by igal1c0de4n** [comment]
Can you be more specific and give an example?

Sorry, pip/python setup is not my expertise...

**Comment by Fmacmak** [comment]
It seems like the problem lies with the version of Python (2.7) you're using to install aws-ssm-copy. To fix this, you'll need to follow these steps:

Go to the official Python website at [python.org](https://www.python.org/downloads/) or find [alternative](https://www.jcchouinard.com/install-python-on-macos/) ways to download Python.

Click on the download link provided on the website, any version of Python that is newer than 3.6 will work.
Follow the instructions provided by the installer to complete the Python installation. 
During the installation, leave the default settings as they are.

Once the installation is finished, you should have the newer version of Python installed on your computer.
Check the version installed using terminal.
`python3 --version`
or 
`python --version`


Now you can retry the installation of aws-ssm-copy using the newly installed Python version, and it should work without any issues.
`pip3 install aws-ssm-copy`

If you encounter any difficulties or have further questions, feel free to ask.
